// Generated by gencpp from file baxter_tictactoe/MsgCell.msg
// DO NOT EDIT!


#ifndef BAXTER_TICTACTOE_MESSAGE_MSGCELL_H
#define BAXTER_TICTACTOE_MESSAGE_MSGCELL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_tictactoe
{
template <class ContainerAllocator>
struct MsgCell_
{
  typedef MsgCell_<ContainerAllocator> Type;

  MsgCell_()
    : state()  {
    }
  MsgCell_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;


    static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  EMPTY;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  BLUE;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  RED;
 

  typedef boost::shared_ptr< ::baxter_tictactoe::MsgCell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_tictactoe::MsgCell_<ContainerAllocator> const> ConstPtr;

}; // struct MsgCell_

typedef ::baxter_tictactoe::MsgCell_<std::allocator<void> > MsgCell;

typedef boost::shared_ptr< ::baxter_tictactoe::MsgCell > MsgCellPtr;
typedef boost::shared_ptr< ::baxter_tictactoe::MsgCell const> MsgCellConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      MsgCell_<ContainerAllocator>::EMPTY =
        
          "empty"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      MsgCell_<ContainerAllocator>::BLUE =
        
          "blue"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      MsgCell_<ContainerAllocator>::RED =
        
          "red"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_tictactoe::MsgCell_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_tictactoe

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'baxter_tictactoe': ['/home/baxterdev/scazLab2_ws/src/baxter_tictactoe/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_common/baxter_core_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_tictactoe::MsgCell_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_tictactoe::MsgCell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_tictactoe::MsgCell_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16e2b4ba8c56c6e7a216c122160a0bb8";
  }

  static const char* value(const ::baxter_tictactoe::MsgCell_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16e2b4ba8c56c6e7ULL;
  static const uint64_t static_value2 = 0xa216c122160a0bb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_tictactoe/MsgCell";
  }

  static const char* value(const ::baxter_tictactoe::MsgCell_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Information from each cell in the board\n\
# Index of each cell in the array:\n\
#            _ _ _ _ _ _\n\
#           |_0_|_1_|_2_|\n\
#           |_3_|_4_|_5_|\n\
#           |_6_|_7_|_8_|\n\
#\n\
# Possible values:\n\
#       0=empty cell\n\
#       1=blue token (X)\n\
#       2=red token (O)\n\
\n\
string EMPTY=empty\n\
string BLUE=blue\n\
string RED=red\n\
\n\
string state\n\
";
  }

  static const char* value(const ::baxter_tictactoe::MsgCell_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgCell_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_tictactoe::MsgCell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_tictactoe::MsgCell_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_TICTACTOE_MESSAGE_MSGCELL_H
