// Generated by gencpp from file baxter_tictactoe/TTTBrainState.msg
// DO NOT EDIT!


#ifndef BAXTER_TICTACTOE_MESSAGE_TTTBRAINSTATE_H
#define BAXTER_TICTACTOE_MESSAGE_TTTBRAINSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_tictactoe
{
template <class ContainerAllocator>
struct TTTBrainState_
{
  typedef TTTBrainState_<ContainerAllocator> Type;

  TTTBrainState_()
    : state(0)  {
    }
  TTTBrainState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;


    enum { INIT = 0u };
     enum { CALIB = 1u };
     enum { READY = 2u };
     enum { WAIT = 3u }; //[UC edition, added wait state. File was generated from msg files]
     enum { MATCH_STARTED = 4u };
     enum { GAME_STARTED = 5u };
     enum { GAME_RUNNING = 6u };
     enum { GAME_FINISHED = 7u };
     enum { MATCH_FINISHED = 8u };
 

  typedef boost::shared_ptr< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> const> ConstPtr;

}; // struct TTTBrainState_

typedef ::baxter_tictactoe::TTTBrainState_<std::allocator<void> > TTTBrainState;

typedef boost::shared_ptr< ::baxter_tictactoe::TTTBrainState > TTTBrainStatePtr;
typedef boost::shared_ptr< ::baxter_tictactoe::TTTBrainState const> TTTBrainStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_tictactoe

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'baxter_tictactoe': ['/home/baxterdev/scazLab2_ws/src/baxter_tictactoe/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_common/baxter_core_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b6cbd204bcff335fca2f7c7c16e4b71";
  }

  static const char* value(const ::baxter_tictactoe::TTTBrainState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b6cbd204bcff335ULL;
  static const uint64_t static_value2 = 0xfca2f7c7c16e4b71ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_tictactoe/TTTBrainState";
  }

  static const char* value(const ::baxter_tictactoe::TTTBrainState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 INIT=0\n\
uint8 CALIB=1\n\
uint8 READY=2\n\
uint8 WAIT=3\n\
uint8 MATCH_STARTED=4\n\
uint8 GAME_STARTED=5\n\
uint8 GAME_RUNNING=6\n\
uint8 GAME_FINISHED=7\n\
uint8 MATCH_FINISHED=8\n\
\n\
uint8 state\n\
";
  }

  static const char* value(const ::baxter_tictactoe::TTTBrainState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTTBrainState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_tictactoe::TTTBrainState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_tictactoe::TTTBrainState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_TICTACTOE_MESSAGE_TTTBRAINSTATE_H
