// Generated by gencpp from file baxter_collaboration_msgs/ArmState.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_ARMSTATE_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_ARMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct ArmState_
{
  typedef ArmState_<ContainerAllocator> Type;

  ArmState_()
    : state()
    , action()
    , object()  {
    }
  ArmState_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , action(_alloc)
    , object(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;




  typedef boost::shared_ptr< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> const> ConstPtr;

}; // struct ArmState_

typedef ::baxter_collaboration_msgs::ArmState_<std::allocator<void> > ArmState;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::ArmState > ArmStatePtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::ArmState const> ArmStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "970438bec580bc76d6e5b3ec112e3e7b";
  }

  static const char* value(const ::baxter_collaboration_msgs::ArmState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x970438bec580bc76ULL;
  static const uint64_t static_value2 = 0xd6e5b3ec112e3e7bULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/ArmState";
  }

  static const char* value(const ::baxter_collaboration_msgs::ArmState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n\
string action\n\
string object\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::ArmState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.action);
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::ArmState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::ArmState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_ARMSTATE_H
