// Generated by gencpp from file baxter_collaboration_msgs/AskFeedbackRequest.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKREQUEST_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct AskFeedbackRequest_
{
  typedef AskFeedbackRequest_<ContainerAllocator> Type;

  AskFeedbackRequest_()
    : ask()  {
    }
  AskFeedbackRequest_(const ContainerAllocator& _alloc)
    : ask(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ask_type;
  _ask_type ask;




  typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AskFeedbackRequest_

typedef ::baxter_collaboration_msgs::AskFeedbackRequest_<std::allocator<void> > AskFeedbackRequest;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackRequest > AskFeedbackRequestPtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackRequest const> AskFeedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e7c2f981aa2ef96a4b8a55a9c6b56ac";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e7c2f981aa2ef96ULL;
  static const uint64_t static_value2 = 0xa4b8a55a9c6b56acULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/AskFeedbackRequest";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ask\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AskFeedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::AskFeedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "ask: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKREQUEST_H
