// Generated by gencpp from file baxter_collaboration_msgs/AskFeedback.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACK_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACK_H

#include <ros/service_traits.h>


#include <baxter_collaboration_msgs/AskFeedbackRequest.h>
#include <baxter_collaboration_msgs/AskFeedbackResponse.h>


namespace baxter_collaboration_msgs
{

struct AskFeedback
{

typedef AskFeedbackRequest Request;
typedef AskFeedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AskFeedback
} // namespace baxter_collaboration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_collaboration_msgs::AskFeedback > {
  static const char* value()
  {
    return "6ace658886065f0a99b6138e3cbeeb85";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedback&) { return value(); }
};

template<>
struct DataType< ::baxter_collaboration_msgs::AskFeedback > {
  static const char* value()
  {
    return "baxter_collaboration_msgs/AskFeedback";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedback&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_collaboration_msgs::AskFeedbackRequest> should match 
// service_traits::MD5Sum< ::baxter_collaboration_msgs::AskFeedback > 
template<>
struct MD5Sum< ::baxter_collaboration_msgs::AskFeedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_collaboration_msgs::AskFeedback >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_collaboration_msgs::AskFeedbackRequest> should match 
// service_traits::DataType< ::baxter_collaboration_msgs::AskFeedback > 
template<>
struct DataType< ::baxter_collaboration_msgs::AskFeedbackRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_collaboration_msgs::AskFeedback >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_collaboration_msgs::AskFeedbackResponse> should match 
// service_traits::MD5Sum< ::baxter_collaboration_msgs::AskFeedback > 
template<>
struct MD5Sum< ::baxter_collaboration_msgs::AskFeedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_collaboration_msgs::AskFeedback >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_collaboration_msgs::AskFeedbackResponse> should match 
// service_traits::DataType< ::baxter_collaboration_msgs::AskFeedback > 
template<>
struct DataType< ::baxter_collaboration_msgs::AskFeedbackResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_collaboration_msgs::AskFeedback >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACK_H
