// Generated by gencpp from file baxter_collaboration_msgs/AskFeedbackResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKRESPONSE_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct AskFeedbackResponse_
{
  typedef AskFeedbackResponse_<ContainerAllocator> Type;

  AskFeedbackResponse_()
    : success(false)
    , reply()  {
    }
  AskFeedbackResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , reply(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reply_type;
  _reply_type reply;




  typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AskFeedbackResponse_

typedef ::baxter_collaboration_msgs::AskFeedbackResponse_<std::allocator<void> > AskFeedbackResponse;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackResponse > AskFeedbackResponsePtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::AskFeedbackResponse const> AskFeedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "921d30aed92ff71b2f7e61c15fd80377";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x921d30aed92ff71bULL;
  static const uint64_t static_value2 = 0x2f7e61c15fd80377ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/AskFeedbackResponse";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   success\n\
string reply\n\
\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AskFeedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::AskFeedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "reply: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_ASKFEEDBACKRESPONSE_H
