// Generated by gencpp from file baxter_collaboration_msgs/DoActionResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONRESPONSE_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct DoActionResponse_
{
  typedef DoActionResponse_<ContainerAllocator> Type;

  DoActionResponse_()
    : success(false)
    , response()  {
    }
  DoActionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , response(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;


    static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  NO_IR_SENSOR;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  OBJ_NOT_IN_DB;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  NO_OBJ;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  ACT_FAILED;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  ACT_NOT_IN_DB;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  ACT_NOT_IMPL;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  INV_KIN_FAILED;
 

  typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DoActionResponse_

typedef ::baxter_collaboration_msgs::DoActionResponse_<std::allocator<void> > DoActionResponse;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionResponse > DoActionResponsePtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionResponse const> DoActionResponseConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::NO_IR_SENSOR =
        
          "No callback from the IR sensor"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::OBJ_NOT_IN_DB =
        
          "Requested object not available in DB"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::NO_OBJ =
        
          "No object detected"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::ACT_FAILED =
        
          "Action failed from user input"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::ACT_NOT_IN_DB =
        
          "Requested action not available in DB"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::ACT_NOT_IMPL =
        
          "Action not implemented"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionResponse_<ContainerAllocator>::INV_KIN_FAILED =
        
          "Inverse Kinematics failed"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ec89fc05093b4058e47026082e37a3c";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ec89fc05093b405ULL;
  static const uint64_t static_value2 = 0x8e47026082e37a3cULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/DoActionResponse";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool   success\n\
\n\
\n\
\n\
\n\
\n\
\n\
string NO_IR_SENSOR   = No callback from the IR sensor\n\
string OBJ_NOT_IN_DB  = Requested object not available in DB\n\
string NO_OBJ         = No object detected\n\
string ACT_FAILED     = Action failed from user input\n\
string ACT_NOT_IN_DB  = Requested action not available in DB\n\
string ACT_NOT_IMPL   = Action not implemented\n\
string INV_KIN_FAILED = Inverse Kinematics failed\n\
\n\
string response\n\
\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::DoActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONRESPONSE_H
