// Generated by gencpp from file baxter_collaboration_msgs/DoActionRequest.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONREQUEST_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct DoActionRequest_
{
  typedef DoActionRequest_<ContainerAllocator> Type;

  DoActionRequest_()
    : action()
    , objects()  {
    }
  DoActionRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _objects_type;
  _objects_type objects;


    static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  LIST_OBJECTS;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  LIST_ACTIONS;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  ACTION_HOME;
     static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  ACTION_RELEASE;
 

  typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DoActionRequest_

typedef ::baxter_collaboration_msgs::DoActionRequest_<std::allocator<void> > DoActionRequest;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionRequest > DoActionRequestPtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::DoActionRequest const> DoActionRequestConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionRequest_<ContainerAllocator>::LIST_OBJECTS =
        
          "list_objects"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionRequest_<ContainerAllocator>::LIST_ACTIONS =
        
          "list_actions"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionRequest_<ContainerAllocator>::ACTION_HOME =
        
          "home"
        
        ;
   

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      DoActionRequest_<ContainerAllocator>::ACTION_RELEASE =
        
          "release"
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132a406c78a872aaac81f149b9f40a7e";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132a406c78a872aaULL;
  static const uint64_t static_value2 = 0xac81f149b9f40a7eULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/DoActionRequest";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
string LIST_OBJECTS     = list_objects\n\
string LIST_ACTIONS     = list_actions\n\
string ACTION_HOME      = home\n\
string ACTION_RELEASE   = release\n\
\n\
string action\n\
\n\
\n\
int16[] objects\n\
\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::DoActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTIONREQUEST_H
