// Generated by gencpp from file baxter_collaboration_msgs/DoAction.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTION_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTION_H

#include <ros/service_traits.h>


#include <baxter_collaboration_msgs/DoActionRequest.h>
#include <baxter_collaboration_msgs/DoActionResponse.h>


namespace baxter_collaboration_msgs
{

struct DoAction
{

typedef DoActionRequest Request;
typedef DoActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DoAction
} // namespace baxter_collaboration_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::baxter_collaboration_msgs::DoAction > {
  static const char* value()
  {
    return "6201132af3b68a8b841f1803943e0d53";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoAction&) { return value(); }
};

template<>
struct DataType< ::baxter_collaboration_msgs::DoAction > {
  static const char* value()
  {
    return "baxter_collaboration_msgs/DoAction";
  }

  static const char* value(const ::baxter_collaboration_msgs::DoAction&) { return value(); }
};


// service_traits::MD5Sum< ::baxter_collaboration_msgs::DoActionRequest> should match 
// service_traits::MD5Sum< ::baxter_collaboration_msgs::DoAction > 
template<>
struct MD5Sum< ::baxter_collaboration_msgs::DoActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_collaboration_msgs::DoAction >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::DoActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_collaboration_msgs::DoActionRequest> should match 
// service_traits::DataType< ::baxter_collaboration_msgs::DoAction > 
template<>
struct DataType< ::baxter_collaboration_msgs::DoActionRequest>
{
  static const char* value()
  {
    return DataType< ::baxter_collaboration_msgs::DoAction >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::DoActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::baxter_collaboration_msgs::DoActionResponse> should match 
// service_traits::MD5Sum< ::baxter_collaboration_msgs::DoAction > 
template<>
struct MD5Sum< ::baxter_collaboration_msgs::DoActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::baxter_collaboration_msgs::DoAction >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::DoActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::baxter_collaboration_msgs::DoActionResponse> should match 
// service_traits::DataType< ::baxter_collaboration_msgs::DoAction > 
template<>
struct DataType< ::baxter_collaboration_msgs::DoActionResponse>
{
  static const char* value()
  {
    return DataType< ::baxter_collaboration_msgs::DoAction >::value();
  }
  static const char* value(const ::baxter_collaboration_msgs::DoActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_DOACTION_H
