// Generated by gencpp from file baxter_collaboration_msgs/ObjectsArray.msg
// DO NOT EDIT!


#ifndef BAXTER_COLLABORATION_MSGS_MESSAGE_OBJECTSARRAY_H
#define BAXTER_COLLABORATION_MSGS_MESSAGE_OBJECTSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <baxter_collaboration_msgs/Object.h>

namespace baxter_collaboration_msgs
{
template <class ContainerAllocator>
struct ObjectsArray_
{
  typedef ObjectsArray_<ContainerAllocator> Type;

  ObjectsArray_()
    : header()
    , objects()  {
    }
  ObjectsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::baxter_collaboration_msgs::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::baxter_collaboration_msgs::Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;




  typedef boost::shared_ptr< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsArray_

typedef ::baxter_collaboration_msgs::ObjectsArray_<std::allocator<void> > ObjectsArray;

typedef boost::shared_ptr< ::baxter_collaboration_msgs::ObjectsArray > ObjectsArrayPtr;
typedef boost::shared_ptr< ::baxter_collaboration_msgs::ObjectsArray const> ObjectsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_collaboration_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'baxter_collaboration_msgs': ['/home/baxterdev/scazLab2_ws/src/baxter_collaboration/baxter_collaboration_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e866a9d87ce3e4706204628f251a2f44";
  }

  static const char* value(const ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe866a9d87ce3e470ULL;
  static const uint64_t static_value2 = 0x6204628f251a2f44ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_collaboration_msgs/ObjectsArray";
  }

  static const char* value(const ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                             header\n\
baxter_collaboration_msgs/Object[] objects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: baxter_collaboration_msgs/Object\n\
\n\
uint32              id\n\
string              name\n\
geometry_msgs/Pose  pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_collaboration_msgs::ObjectsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::baxter_collaboration_msgs::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_COLLABORATION_MSGS_MESSAGE_OBJECTSARRAY_H
