// Generated by gencpp from file svox_tts/Speech.msg
// DO NOT EDIT!


#ifndef SVOX_TTS_MESSAGE_SPEECH_H
#define SVOX_TTS_MESSAGE_SPEECH_H

#include <ros/service_traits.h>


#include <svox_tts/SpeechRequest.h>
#include <svox_tts/SpeechResponse.h>


namespace svox_tts
{

struct Speech
{

typedef SpeechRequest Request;
typedef SpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speech
} // namespace svox_tts


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svox_tts::Speech > {
  static const char* value()
  {
    return "9c3f446da6b1955451e6967a08f80cbd";
  }

  static const char* value(const ::svox_tts::Speech&) { return value(); }
};

template<>
struct DataType< ::svox_tts::Speech > {
  static const char* value()
  {
    return "svox_tts/Speech";
  }

  static const char* value(const ::svox_tts::Speech&) { return value(); }
};


// service_traits::MD5Sum< ::svox_tts::SpeechRequest> should match 
// service_traits::MD5Sum< ::svox_tts::Speech > 
template<>
struct MD5Sum< ::svox_tts::SpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svox_tts::Speech >::value();
  }
  static const char* value(const ::svox_tts::SpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svox_tts::SpeechRequest> should match 
// service_traits::DataType< ::svox_tts::Speech > 
template<>
struct DataType< ::svox_tts::SpeechRequest>
{
  static const char* value()
  {
    return DataType< ::svox_tts::Speech >::value();
  }
  static const char* value(const ::svox_tts::SpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svox_tts::SpeechResponse> should match 
// service_traits::MD5Sum< ::svox_tts::Speech > 
template<>
struct MD5Sum< ::svox_tts::SpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svox_tts::Speech >::value();
  }
  static const char* value(const ::svox_tts::SpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svox_tts::SpeechResponse> should match 
// service_traits::DataType< ::svox_tts::Speech > 
template<>
struct DataType< ::svox_tts::SpeechResponse>
{
  static const char* value()
  {
    return DataType< ::svox_tts::Speech >::value();
  }
  static const char* value(const ::svox_tts::SpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVOX_TTS_MESSAGE_SPEECH_H
