// Generated by gencpp from file svox_tts/SpeechResponse.msg
// DO NOT EDIT!


#ifndef SVOX_TTS_MESSAGE_SPEECHRESPONSE_H
#define SVOX_TTS_MESSAGE_SPEECHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace svox_tts
{
template <class ContainerAllocator>
struct SpeechResponse_
{
  typedef SpeechResponse_<ContainerAllocator> Type;

  SpeechResponse_()
    : success(false)
    , response()
    , value(0)  {
    }
  SpeechResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , response(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;

   typedef int32_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::svox_tts::SpeechResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::svox_tts::SpeechResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechResponse_

typedef ::svox_tts::SpeechResponse_<std::allocator<void> > SpeechResponse;

typedef boost::shared_ptr< ::svox_tts::SpeechResponse > SpeechResponsePtr;
typedef boost::shared_ptr< ::svox_tts::SpeechResponse const> SpeechResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::svox_tts::SpeechResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::svox_tts::SpeechResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace svox_tts

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::svox_tts::SpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::svox_tts::SpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svox_tts::SpeechResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svox_tts::SpeechResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svox_tts::SpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svox_tts::SpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::svox_tts::SpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9886b801160c86d6bc3926cd14172088";
  }

  static const char* value(const ::svox_tts::SpeechResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9886b801160c86d6ULL;
  static const uint64_t static_value2 = 0xbc3926cd14172088ULL;
};

template<class ContainerAllocator>
struct DataType< ::svox_tts::SpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "svox_tts/SpeechResponse";
  }

  static const char* value(const ::svox_tts::SpeechResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::svox_tts::SpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   success\n\
string response\n\
int32  value\n\
\n\
";
  }

  static const char* value(const ::svox_tts::SpeechResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::svox_tts::SpeechResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.response);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::svox_tts::SpeechResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::svox_tts::SpeechResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVOX_TTS_MESSAGE_SPEECHRESPONSE_H
